Code review session
sheldonwafula/my-code-review pull request #1
Opened 2023-02-20 10:51 UTC by sheldonwafula

In this pull request:
I have created a new repo.
I have added an HTML and CSS file.
I have corrected linter errors.

2023-02-20 11:34 UTC, sheldonwafula commented on index.html
> +    <p id = "description">We are going to design this survey form for microverse admisssion trials</p>
Please add this section into header tags for sematic reasons.

2023-02-20 11:43 UTC, sheldonwafula reviewed
Changes required:
Kindly Read my comments and make the necessary changes.

2023-02-20 11:43 UTC, sheldonwafula commented on index.html
> +    <p id = "description">We are going to design this survey form for microverse admisssion trials</p>
Please add this section into the header tag for sematic reasons.

2023-02-20 11:43 UTC, sheldonwafula commented on index.html
> +</div>
I would suggest you add this section to the main tags for sematic reasons.

2023-02-20 12:02 UTC, Shedrack-Sunday requested changes
Hi @sheldonwafula     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
  
Required Changes ♻️

- [x] Firstly, your summary looks very short, and if you agree with me, it's not quite professional 😉 . Please use my summary here as a reference, to make your review reference detailed and professional 👍 
- [ ] Secondly, You did a good job on the reviews, but I'll advise you frequently use emojis to show friendliness and Grammarly for proper sentence structure 👏 

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-20 12:02 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Your License path seems to be failing. kindly fix this 👍

2023-02-20 12:02 UTC, Shedrack-Sunday commented on index.html
> +    <p id = "description">We are going to design this survey form for microverse admisssion trials</p>
- [ ] Nice review you made here. However, you highlighted from line one to line `13`. Lines `1-8` are not meant to be under the `header tag. so please be specific when highlighting the section that needs changes 👍 
- [ ] Also, just as you saw me do in point one, always use black strings to specify tags. `header` instead of header 👍

2023-02-20 12:02 UTC, Shedrack-Sunday commented on index.html
> +</div>
- [ ] Nice efforts 👏 , But just as you mentioned the semantic reasons, it would be great to go into detail on why that's important to do. This way, we give the person a more clear path on changes to make 👍

2023-02-21 06:12 UTC, sheldonwafula reviewed
Changes required:
Read through the comments and make the necessary changes.

2023-02-21 06:12 UTC, sheldonwafula commented on index.html
> +    <p id = "description">We are going to design this survey form for microverse admisssion trials</p>
Please I would suggest you add this section to the `header` tag for semantic reasons. This will make your code clean and easy to fix bugs.

2023-02-21 06:12 UTC, sheldonwafula commented on index.html
> +</div>
Please consider adding this section to the `main` tag. this will make your code easier for people to navigate when updating features.

2023-02-21 06:21 UTC, AdnanOlarmmi approved these changes
Hi @sheldonwafula,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice work ignoring appropriate files.
- Professional README.

## Optional suggestions

- [ ] Please, I suggest that you start using emojis in you code reviews, this will make your reviews more friendly 👽 😁.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 06:25 UTC, merged